#!/bin/bash

# init update
echo "Updating and upgrading..."
sudo apt-get update > /dev/null
sudo apt-get upgrade > /dev/null

# install packages
if [ -f packages ]; then
  echo "Installing packages..."
  pkgmgr="apt-get -y"
  while read -r pkg || [[ -n $pkg ]]; do
    if [[ $pkg == "#"* ]]; then
      pkgmgr=$(echo $pkg | cut -d'#' -f 2)
    else
      echo "Installing "$pkg" with "$pkgmgr"..."
      sudo $pkgmgr install $pkg > /dev/null
    fi
  done < packages
fi

echo -n "If you have an SSH server input the address now (blank=none):"
read sshaddr

if [[ ! -z $sshaddr ]]; then
  "Creating $sshaddr variable..."
  echo 'SSH_ADDRESS="'$sshaddr'"' >> home/bin/.utilrc.rb
fi

if [ -d home ]; then
  echo "Adding home files and folders..."
	cp -a home/. ~/
  if [ -d ~/bin ]; then
    find ~/bin -type f -exec chmod +x {} \;
  fi
fi

. ~/.bashrc
